spring:
  datasource:   #读写分离配置数据源
    systemRead:
      url: jdbc:mysql://123.206.78.174:3306/rong_system?characterEncoding=utf-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
    systemWrite:
      url: jdbc:mysql://123.206.78.174:3306/rong_system?characterEncoding=utf-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver

  thymeleaf:
     cache: false
     mode: LEGACYHTML5   #去掉HTML标签校验

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/rong/**/**/*Mapper.xml
  typeAliasesPackage: com.byk.**.**.entity
server:
  port: 8888

#logging.level.com.dy.springboot.server.mapper=debug
logging:
  level:
    com.byk.rong.system.mapper.*: debug