eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1028/eureka/ #这是刚才创建的eureka注册地址

server:
  port: 1030
spring:
  application:
    name: system_server    #服务名称，这里写什么，注册中心就显示什么，以后调用这个服务就写这个名
  datasource:   #读写分离配置数据源
    systemRead:
      url: jdbc:mysql://123.206.78.174:3306/rong_system?characterEncoding=utf-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
    systemWrite:
      url: jdbc:mysql://123.206.78.174:3306/rong_system?characterEncoding=utf-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
    bokeRead:
      url: jdbc:mysql://123.206.78.174:3306/boke?characterEncoding=utf-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
    bokeWrite:
      url: jdbc:mysql://123.206.78.174:3306/boke?characterEncoding=utf-8
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
     cache: false
     mode: LEGACYHTML5   #去掉HTML标签校验
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
#  profiles:
#      active: dev


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/rong/**/**/*Mapper.xml
  typeAliasesPackage: com.byk.rong.**.entity


#logging.level.com.dy.springboot.server.mapper=debug
# 1.这里必须先配置root日志级别，也就是系统的，然后再单独的配置mapper日志级别
# 2.不知道为什么中间加* 整合多个包不好使
logging:
  level:
    root: info
    com.byk.rong.system.mapper: debug
    com.byk.rong.boke.mapper: debug


byk:
  pagePath: /usr/local/image/boke/


